### ISSUE TITLE
Index.html ticketing section

### ISSUE THREAD

**Issue by DcodeNischal** [dhunganaPradeep/TEDxKamalPokhari#5]
The section info doesnot match with the main tickets.html page. Also, I think this section should be small and attractive rather than big icons and divs. It may be one simple div leading to the main ticketing page.

**Comment by dhunganaPradeep** [comment]
Removed the ticket section from index.html as there was no need to include it here as we redirected any users who clicked on register to the ticket section and added buttons to key locations on the page for easy user navigation to ticket page.
